config/routes.rb
Rails.application.routes.draw do
  devise_for :utilisateurs
  resources :films

  root 'films#index'

end

app/models/film.rb
class Film < ActiveRecord::Base
belongs_to :utilisateur
 
 has_attached_file :image, styles: { medium: "400x600#" }
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :films
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_utilisateur!, except: [:index, :show]
  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = current_utilisateur.films.build
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = current_utilisateur.films.build(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:titre, :description, :durée, :réalisateur, :note, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for @film, html: { multipart: true } do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :durée %><br>
    <%= f.text_field :durée %>
  </div>
  <div class="field">
    <%= f.label :réalisateur %><br>
    <%= f.text_field :réalisateur %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editer film</h1>

<%= render 'form' %>

<%= link_to 'Voir', @film %> |
<%= link_to 'Retour', films_path %>

app/views/films/index.html.erb
<% if !utilisateur_signed_in? %>
  <div class="jumbotron">
    <h1Vos critiques de film preféré !</h1>
    <p>Ancien ou nouveau film, peu importe toute les informations sont ici !!!</p>
    <p><%= link_to "Inscrivez-vous pour écrire un commentaire", new_utilisateur_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @films.each do |film| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag film.image.url(:medium), class: 'image'), film %>
      </div>
    </div>
  <% end %>
</div>

app/views/films/new.html.erb
<h1>Nouveau film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @film.image.url(:medium) %>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Titre:</strong></td>
                <td><%= @film.titre %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @film.description %></td>
              </tr>
              <tr>
                <td><strong>Durée:</strong></td>
                <td><%= @film.durée %></td>
              </tr>
              <tr>
                <td><strong>Réalisateur:</strong></td>
                <td><%= @film.réalisateur %></td>
              </tr>
              <tr>
                <td><strong>Note:</strong></td>
                <td><%= @film.note %></td>
              </tr>
            </tbody>
          </table>
        </div>
     </div>
    </div>
  </div>
</div> 

<%= link_to 'Editer', edit_film_path(@film) %> |
<%= link_to 'Retour', films_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Critiques de film", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if utilisateur_signed_in? %>
          <li><%= link_to "Nouveau Films", new_film_path, class: "active" %></li>
          <li><%= link_to "Compte", edit_utilisateur_registration_path %></li>
        <% else %>
          <li><%= link_to "Inscrivez-vous", new_utilisateur_registration_path, class: "active" %></li>
          <li><%= link_to "Se connecter", new_utilisateur_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class ="form-group">
          <input type="text" class="form-control" placeholder="Recherche">
        </div>  
	<button type="submit"  class="btn btn-default">Submit</button>
        </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebFilms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/header' %>
  <div class="container">  
<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
       <% end %>

<%= yield %>

</body>
</html>